version: '3.8'
services:
  app-db:
    image: mysql:8.1
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - database:/var/lib/mysql
    networks:
      - app-network

  app:
    image: sb-products-api
    command: nvm spring-boot:run
    restart: on-failure
    build: ./app
    env_file:
      - .env
    ports:
      - '8080:8080'
    environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://app-db:${DB_PORT}/${DB_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
       SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
       SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - app-db
    networks:
      - app-network
    stdin_open: true
    tty: true

  sonar-qube:
    image: sonarqube:8.9-community
    depends_on:
      - sonar-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: admin
      SONAR_JDBC_PASSWORD: admin
    volumes:
      - sonarqube_data:/opt/SonarQube/data
      - sonarqube_extensions:/opt/SonarQube/extensions
      - sonarqube_logs:/opt/SonarQube/logs
    ports:
      - '9000:9000'

  sonar-db:
    image: postgres:13
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - app-network
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    networks:
      - app-network

volumes:
  database:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
  prometheus_data:
  grafana_data:

networks:
  app-network:
    driver: bridge